id: A883333F8
title: 'The Rain of Virtue and Goodness: A Short Practice for Consecrating Representations
  of Enlightened Body, Speech and Mind'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.778467
  last_modified_at: 2022-03-01 05:32:40.778470
