id: A883333F8
title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.659934
  last_modified_at: 2022-03-01 05:32:40.659946
