id: A883333F8
title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
  ‘The Heart Essence of the Sublime Lady of Immortality’
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.664415
  last_modified_at: 2022-03-01 05:32:40.664418
