id: A883333F8
title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa Lhundrupma)
  from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.776742
  last_modified_at: 2022-03-01 05:32:40.776745
