id: A883333F8
title: Yeshe Tsogyal's Prayer
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.845615
  last_modified_at: 2022-03-01 05:32:40.845618
