id: A883333F8
title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected Words
  of the Buddha
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.737988
  last_modified_at: 2022-03-01 05:32:40.737991
