id: A883333F8
title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.802569
  last_modified_at: 2022-03-01 05:32:40.802571
