id: A883333F8
title: 'Opening the Door to Great Bliss: An Aspiration Towards the Realm of Abhirati'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.717420
  last_modified_at: 2022-03-01 05:32:40.717423
