id: A883333F8
title: 'The Vajra Lute: A Brief Fulfilment for the Guru Practice of VidyÄdhara-Assembly'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.809905
  last_modified_at: 2022-03-01 05:32:40.809909
