id: A883333F8
title: The Means for Accomplishment called the Blazing Wheel
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.751477
  last_modified_at: 2022-03-01 05:32:40.751480
