id: A883333F8
title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives of the
  Supreme Holders of the Non-Sectarian Teachings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.749268
  last_modified_at: 2022-03-01 05:32:40.749270
