id: A883333F8
title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.769968
  last_modified_at: 2022-03-01 05:32:40.769971
