id: A883333F8
title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.656253
  last_modified_at: 2022-03-01 05:32:40.656256
