id: A883333F8
title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage of Zabtik
  Drolchok'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.747094
  last_modified_at: 2022-03-01 05:32:40.747097
