id: A883333F8
title: Verses of Confession 'Düsum Deshekma'
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.830753
  last_modified_at: 2022-03-01 05:32:40.830756
