id: A883333F8
title: Ārya Mañjuśrī Tantra Garbha
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.848518
  last_modified_at: 2022-03-01 05:32:40.848521
