id: A883333F8
title: 'Bright Light of the Sun: A Simple Fire Offering Based on a Single Substance'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.665577
  last_modified_at: 2022-03-01 05:32:40.665580
