id: A883333F8
title: The Spontaneous Vajra Song of Fulfilment and Confession
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.790088
  last_modified_at: 2022-03-01 05:32:40.790091
