id: A883333F8
title: 'The Bestowal of Supreme Immortality: A Prayer to the Lineage of Mitrayogin’s
  White and Red Amitāyus'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.726334
  last_modified_at: 2022-03-01 05:32:40.726338
