id: A883333F8
title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The Nucleus
  of Blessings’
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.773853
  last_modified_at: 2022-03-01 05:32:40.773856
