id: A883333F8
title: 'The Shower of Great Bliss: A Prayer to the Lineage of the Female Awareness-Holder
  (Yumka)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.782266
  last_modified_at: 2022-03-01 05:32:40.782269
