id: A883333F8
title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the Life
  and Liberation of the Guru from Uḍḍiyāna'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.668483
  last_modified_at: 2022-03-01 05:32:40.668486
