id: A883333F8
title: Prayer for the Future of the Dharma
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.720718
  last_modified_at: 2022-03-01 05:32:40.720721
