id: A883333F8
title: The Ultimate Inexpressible Confession (Yeshe Kuchokma)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.807408
  last_modified_at: 2022-03-01 05:32:40.807411
