id: A883333F8
title: 'Emptying the Hells from their Very Depths: The Sovereign Practice for the
  Confession of all Impairments and Breakages of Vows and all Negative Actions and
  Obscurations'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.676679
  last_modified_at: 2022-03-01 05:32:40.676685
