id: A883333F8
title: 'The Offering Clouds of the Indestructible Ladies of Sound: Concise Garland
  of Offerings of the Sixteen Vajra Goddesses'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.761845
  last_modified_at: 2022-03-01 05:32:40.761848
