id: A883333F8
title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.686531
  last_modified_at: 2022-03-01 05:32:40.686534
