id: A883333F8
title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
  Practice that Unites the Oral, Treasure and Visionary Teachings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.792982
  last_modified_at: 2022-03-01 05:32:40.792985
