id: A883333F8
title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
  the Four Empowerments
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.662729
  last_modified_at: 2022-03-01 05:32:40.662734
