id: A883333F8
title: 'A Glimpse of the Crucial Points: The VidyÄdhara''s Manual of Concealed Instructions'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.652295
  last_modified_at: 2022-03-01 05:32:40.652298
