id: A883333F8
title: Offering the Eight Auspicious Substances and Seven Emblems of Royalty
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.713717
  last_modified_at: 2022-03-01 05:32:40.713720
