id: A883333F8
title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary of the
  Chronicles of Padma, The Life and Liberation of the Precious Guru of Uḍḍiyāna'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.648945
  last_modified_at: 2022-03-01 05:32:40.648954
