id: A883333F8
title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of the
  Guru (Lama Sangdü)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.732447
  last_modified_at: 2022-03-01 05:32:40.732450
