id: A883333F8
title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
  Heart Drop'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.727865
  last_modified_at: 2022-03-01 05:32:40.727867
