id: A883333F8
title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the Liberational
  Life of the Omniscient Jamyang Khyentse Wangpo'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.755118
  last_modified_at: 2022-03-01 05:32:40.755121
