id: A883333F8
title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.671399
  last_modified_at: 2022-03-01 05:32:40.671402
