id: A883333F8
title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities Based
  on a Single Substance to Easily Conclude Approach and Accomplishment'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.678837
  last_modified_at: 2022-03-01 05:32:40.678841
