id: A883333F8
title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
  of the Vast Expanse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.780215
  last_modified_at: 2022-03-01 05:32:40.780217
