id: A883333F8
title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart Essence
  of the Vast Expanse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.826155
  last_modified_at: 2022-03-01 05:32:40.826162
