id: A883333F8
title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.705810
  last_modified_at: 2022-03-01 05:32:40.705813
