id: A883333F8
title: The Aspiration of the Vajradhātu Maṇḍala
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.724520
  last_modified_at: 2022-03-01 05:32:40.724522
