id: A883333F8
title: The Mountain Smoke Offering (Riwo Sangchö)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:32:40.759223
  last_modified_at: 2022-03-01 05:32:40.759225
